version: '3.5'

services:
  build:
    image: microsoft/dotnet:2.1-sdk
    volumes:
    - ..:/src
    working_dir: /src/Challenge1
    command: /bin/bash -c "dotnet publish Challenge1.csproj -c Release -o ./Docker/publish"
